name: egmde
adopt-info: egmde
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
base: core18

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  EGMDE_LAUNCH_PREFIX: "env -u __EGL_VENDOR_LIBRARY_DIRS --"

apps:
  egmde:
    command: bin/egmde.launcher

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  egmde:
    after: [recipe-version]
    override-pull: |
      snapcraftctl pull
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $server_version-mir$mir_version-snap$recipe_version
      if echo $mir_version | grep dev; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    plugin: cmake-with-ppa
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
    stage-packages:
      - mir-graphics-drivers-desktop
      - libmiral3
      - libfreetype6
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/
      egmde_setup.sh: bin/

  mesa:
    plugin: meson
    source: https://gitlab.freedesktop.org/mesa/mesa.git
    source-tag: mesa-18.2.8
    source-depth: 1
    meson-parameters:
    - --buildtype=debug
    - --prefix=/usr
    build-packages:
    - mesa-common-dev
    - libglvnd-dev
    - libdrm-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxcb-dri3-dev
    - libxcb-present-dev
    - libxcb-sync-dev
    - libxshmfence-dev
    - libxcb-dri2-0-dev
    - libxcb-glx0-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxxf86vm-dev
    - x11proto-dev
    - libxrandr-dev
    - libexpat1-dev
    - llvm
    - libelf-dev
    - python
    - python-mako
    - bison
    - flex
    - wayland-protocols
    - libwayland-egl-backend-dev
    # configflags:
    # - --enable-llvm
    # - --with-dri-drivers=i965
    # - --enable-debug
    stage-packages:
    - libdrm-amdgpu1
    - libdrm-intel1
    - libdrm-nouveau2
    - libdrm-radeon1
    - libdrm2
    - libelf1
    - libexpat1
    - libgcc1
    - libglapi-mesa
    - libllvm7
    - libsensors4
    - libstdc++6
    - zlib1g
    - libllvm6.0
    - libxdamage1
    - libxext6
    - libxxf86vm1
    - libxcb-glx0
    - libxcb-randr0
    # stage-packages:
    # - libgl1-mesa-dri
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
    stage:
      - -usr/lib/x86_64-linux-gnu/libEGL.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libGLESv2.so.2.0.0
      - -usr/lib/x86_64-linux-gnu/libgbm.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
